### ISSUE TITLE
app.json Error

### ISSUE THREAD

**Issue by Quiec** [muhammedfurkan/Spotify-Telegram-Bio-Updater#1]
<img width="584" alt="Ekran Resmi 2019-11-27 19 43 46" src="https://user-images.githubusercontent.com/46392667/69742741-50dcf280-114e-11ea-86b4-6c10984d75d1.png">

i dont know why i am getting this error

**Comment by muhammedfurkan** [comment]
> <img alt="Ekran Resmi 2019-11-27 19 43 46" width="584" src="https://user-images.githubusercontent.com/46392667/69742741-50dcf280-114e-11ea-86b4-6c10984d75d1.png">
> 
> i dont know why i am getting this error

issue has been fixed [that commit](https://github.com/muhammedfurkan/Spotify-Telegram-Bio-Updater/commit/95ac9896aba88fc6a7b8507610c0943d8babe6f6)

**Comment by Quiec** [comment]
same error. not working.

**Comment by muhammedfurkan** [comment]
> same error. not working.

create one app.json thats simple. take look at the google or heroku app.json examples...
