### ISSUE TITLE
can't create database.json, following are the errors while running generate.py and i don't seem to fix this issue on my own.....if you could help, much appreciated

### ISSUE THREAD

**Issue by thewickedkarma** [muhammedfurkan/Spotify-Telegram-Bio-Updater#3]
```Traceback (most recent call last):
  File "generate.py", line 41, in <module>
    main()
  File "generate.py", line 36, in main
    loop.run_until_complete(generate())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "generate.py", line 25, in generate
    "access_token": save["access_token"],
KeyError: 'access_token'
```

**Comment by muhammedfurkan** [comment]
Firstly;

- Get your spotify **client_id** and your **client_secret** from https://developer.spotify.com/dashboard/.
- Open the following link (**change CLIENT_ID to you client_id**): https://accounts.spotify.com/authorize?client_id=CLIENT_ID&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fcallback&scope=user-read-playback-state%20user-read-currently-playing
- After you grant permission, you get redirected to https://example.com/callback?code=**<your_code_here>** , **Copy everything after the code.** **this is your initial token**
- Paste all these values in their respective variables at [constants.py](https://github.com/muhammedfurkan/Spotify-Telegram-Bio-Updater/blob/master/constants.py).

**Comment by thewickedkarma** [comment]
Yeah, i did exactly the same....but I still got the same error
